name: Promote Docker images
description: Promotes the Docker image for each Server.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        for d in server/*/; do
          image_name="us-docker.pkg.dev/circular-genius/limber/limber-$(basename "$d")-server"
          gcloud artifacts docker tags add "$image_name:$GITHUB_SHA_SHORT" "$image_name"
        done
