name: Gradle build
description: |
  Builds the Gradle project, split across multiple steps.
  Test failures are ignored so that all tests run, giving us a comprehensive JUnit report.
  After tests finish, this report is uploaded and will cause failure if there are failing tests.
inputs:
  postgresPassword:
    description: Password for the locally running Postgres instance.
    required: true
  postgresUsername:
    description: Username for the locally running Postgres instance.
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: ./gradlew assemble
    - shell: bash
      env:
        LIMBER_TEST_SQL_USERNAME: ${{ inputs.postgresUsername }}
        LIMBER_TEST_SQL_PASSWORD: ${{ inputs.postgresPassword }}
      run: ./gradlew check -PignoreTestFailures # Ignore failures for a comprehensive JUnit report.
    - shell: bash
      run: ./gradlew build
    - uses: dorny/test-reporter@v1.6.0 # https://github.com/dorny/test-reporter/releases.
      if: always()
      with:
        name: JUnit tests
        path: '**/build/test-results/test/TEST-*.xml'
        reporter: java-junit
        fail-on-error: false
