monolithBaseUrl: http://localhost:55100

authentication:
  mechanisms:
    - type: JWT
      issuer: https://limberapp.io/
      leeway: 300 # 5 minutes
      secret:
        type: PLAINTEXT
        value: limber
    - type: JWK
      issuer: https://limber.auth0.com/
      leeway: 300 # 5 minutes
      domain: limber.auth0.com

clock:
  type: REAL

sqlDatabase:
  jdbcUrl:
    type: PLAINTEXT
    value: jdbc:postgresql://localhost/limber
  username:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_DEV_POSTGRES_USERNAME
    defaultValue: postgres
  password:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_DEV_POSTGRES_PASSWORD
  connectionTimeout: 1000
  maximumPoolSize: 2

uuids:
  generation: RANDOM
