monolithBaseUrl: http://localhost:55100

authentication:
  mechanisms:
    - type: UNSIGNED_JWT
      leeway: 0

sqlDatabase:
  jdbcUrl:
    type: PLAINTEXT
    value: jdbc:postgresql://localhost/limber_test
  username:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_TEST_POSTGRES_USERNAME
    defaultValue: postgres
  password:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_TEST_POSTGRES_PASSWORD
  connectionTimeout: 1000
  maximumPoolSize: 2

clock:
  type: FIXED

uuids:
  generation: DETERMINISTIC
