monolithBaseUrl: http://localhost:55100

authentication:
  mechanisms:
    - type: JWT
      issuer: https://limberapp.io/
      leeway: 300 # 5 minutes
      secret:
        type: PLAINTEXT
        value: limber
    - type: JWK
      issuer: https://limber.auth0.com/
      leeway: 300 # 5 minutes
      domain: limber.auth0.com

clock:
  type: REAL

uuids:
  generation: RANDOM
