monolithBaseUrl: http://limber-monolith-server

authentication:
  mechanisms:
    - type: JWT
      issuer: https://limberapp.io/
      leeway: 20 # 20 seconds
      secret:
        type: ENVIRONMENT_VARIABLE
        name: LIMBER_PROD_JWT_SECRET
    - type: JWK
      issuer: https://limber.auth0.com/
      leeway: 20 # 20 seconds
      domain: limber.auth0.com

clock:
  type: REAL

uuids:
  generation: RANDOM
