runtime: java17

entrypoint: java -XshowSettings:vm -XX:MaxRAMPercentage=80 -jar server.jar

handlers:
  - url: /.*
    script: auto
    secure: always

instance_class: F2

automatic_scaling:
  max_concurrent_requests: 64

inbound_services:
  - warmup

env_variables:
  LIMBER_CONFIG: production
  LIMBER_SQL_JDBC_URL: jdbc:postgresql://localhost/limber
  LIMBER_SQL_USERNAME: app_engine
  LIMBER_SQL_INSTANCE_NAME: limberapp-io:us-central1:limber
