apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: limber-backend
      namespace: limber
      labels:
        instance: limber
    spec:
      ports:
        - port: 80
          targetPort: 55100
      selector:
        app: limber-backend
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: limber-backend
      namespace: limber
      labels:
        instance: limber
    spec:
      selector:
        matchLabels:
          app: limber-backend
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      template:
        metadata:
          labels:
            app: limber-backend
        spec:
          containers:
            - name: limber-backend
              image: registry.digitalocean.com/limber/limber-backend:master
              resources:
                requests:
                  cpu: 250m
                  memory: 500Mi
                limits:
                  cpu: 250m
                  memory: 500Mi
              ports:
                - containerPort: 55100
              env:
                - name: LIMBER_PROD_POSTGRES_JDBC_URL
                  value: jdbc:postgresql://db-limber-prod-do-user-7022079-0.db.ondigitalocean.com:25060/limber?sslmode=require
                - name: LIMBER_PROD_POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: limber-prod-postgres-credentials
                      key: password
              livenessProbe:
                httpGet:
                  path: /health-check
                  port: 55100
                initialDelaySeconds: 5
                periodSeconds: 5
              readinessProbe:
                httpGet:
                  path: /health-check
                  port: 55100
                initialDelaySeconds: 5
                periodSeconds: 5
          imagePullSecrets:
            - name: limber-do-registry
