apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: limber-react
      namespace: limber
      labels:
        instance: limber
    spec:
      ports:
        - port: 80
          targetPort: 80
      selector:
        app: limber-react
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: limber-react
      namespace: limber
      labels:
        instance: limber
    spec:
      selector:
        matchLabels:
          app: limber-react
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      template:
        metadata:
          labels:
            app: limber-react
        spec:
          containers:
            - name: limber-react
              image: registry.digitalocean.com/limber/limber-react:master
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 80m
                  memory: 100Mi
                limits:
                  cpu: 200m
                  memory: 400Mi
              ports:
                - containerPort: 80
              livenessProbe:
                httpGet:
                  path: /
                  port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /
                  port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
                successThreshold: 5
                failureThreshold: 3
          imagePullSecrets:
            - name: registry-limber
