apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: limber-graphql-server
      namespace: limber
      labels:
        instance: limber
    spec:
      ports:
        - port: 80
          targetPort: 55200
      selector:
        app: limber-graphql-server
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: limber-graphql-server
      namespace: limber
      labels:
        instance: limber
    spec:
      selector:
        matchLabels:
          app: limber-graphql-server
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      template:
        metadata:
          labels:
            app: limber-graphql-server
        spec:
          containers:
            - name: limber-graphql-server
              image: registry.digitalocean.com/limber/limber-graphql-server:master
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 200m
                  memory: 400Mi
                limits:
                  cpu: 400m
                  memory: 800Mi
              ports:
                - containerPort: 55200
              env:
                - name: LIMBER_CONFIG
                  value: prod
                - name: LIMBER_PROD_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: limber-prod-auth
                      key: jwt-secret
              livenessProbe:
                httpGet:
                  path: /health-check
                  port: 55200
                initialDelaySeconds: 30
                periodSeconds: 5
                successThreshold: 1
                failureThreshold: 12
              readinessProbe:
                httpGet:
                  path: /health-check
                  port: 55200
                initialDelaySeconds: 30
                periodSeconds: 5
                successThreshold: 5
                failureThreshold: 12
          imagePullSecrets:
            - name: registry-limber
