apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: Service
    metadata:
      name: limber-web
      namespace: limber
      labels:
        instance: limber
    spec:
      ports:
        - port: 80
          targetPort: 80
      selector:
        app: limber-web

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: limber-web
      namespace: limber
      labels:
        instance: limber
    spec:
      selector:
        matchLabels:
          app: limber-web
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      template:
        metadata:
          labels:
            app: limber-web
        spec:
          serviceAccountName: limber
          containers:
            - name: limber-web
              image: gcr.io/limberio/limber-web:master
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 50m
                  memory: 100M
                limits:
                  cpu: 200m
                  memory: 400M
              ports:
                - containerPort: 80
              livenessProbe:
                httpGet:
                  path: /
                  port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /
                  port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
                successThreshold: 5
                failureThreshold: 3
