apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: Service
    metadata:
      name: limber-monolith-server
      namespace: limber
      labels:
        instance: limber
    spec:
      ports:
        - port: 80
          targetPort: 55100
      selector:
        app: limber-monolith-server

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: limber-monolith-server
      namespace: limber
      labels:
        instance: limber
    spec:
      selector:
        matchLabels:
          app: limber-monolith-server
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      template:
        metadata:
          labels:
            app: limber-monolith-server
        spec:
          serviceAccountName: limber
          containers:
            - name: limber-monolith-server
              image: gcr.io/limberio/limber-monolith-server:master
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 200m
                  memory: 400M
                limits:
                  cpu: 500m
                  memory: 2G
              ports:
                - containerPort: 55100
              env:
                - name: LIMBER_CONFIG
                  value: prod
                - name: LIMBER_PROD_POSTGRES_JDBC_URL
                  value: jdbc:postgresql://localhost/limber
                - name: LIMBER_PROD_POSTGRES_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: username
                - name: LIMBER_PROD_POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-credentials
                      key: password
                - name: LIMBER_PROD_JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: jwt-auth
                      key: secret
              livenessProbe:
                httpGet:
                  path: /health-check
                  port: 55100
                initialDelaySeconds: 15
                periodSeconds: 5
                successThreshold: 1
                failureThreshold: 12
              readinessProbe:
                httpGet:
                  path: /health-check
                  port: 55100
                initialDelaySeconds: 15
                periodSeconds: 5
                successThreshold: 6
                failureThreshold: 12
            - name: cloud-sql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:1.22.0 # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
              command:
                - "/cloud_sql_proxy"
                - "-instances=limberio:us-central1:limber=tcp:5432"
              resources:
                requests:
                  cpu: 25m
                  memory: 50M
                limits:
                  cpu: 100m
                  memory: 200M
              securityContext:
                runAsNonRoot: true
