apiVersion: v1
kind: Service
metadata:
  name: limber-backend
  namespace: limber-prod
  labels:
    instance: limber-prod
spec:
  ports:
    - port: 80
      targetPort: 55100
  selector:
    app: limber-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limber-backend
  namespace: limber-prod
  labels:
    instance: limber-prod
spec:
  selector:
    matchLabels:
      app: limber-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: limber-backend
    spec:
      containers:
        - name: limber-backend
          image: registry.digitalocean.com/limber/limber-backend:master
          ports:
            - containerPort: 55100
          env:
            - name: LIMBER_PROD_POSTGRES_JDBC_URL
              value: jdbc:postgresql://db-limber-prod-do-user-7022079-0.db.ondigitalocean.com:25060/limber?sslmode=require
            - name: LIMBER_PROD_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: limber-prod-postgres-credentials
                  key: password
      imagePullSecrets:
        - name: limber-prod-do-registry
