apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: limber
      labels:
        instance: limber
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: limber
      namespace: limber
      labels:
        instance: limber
    spec:
      hard:
        cpu: 1000m
        memory: 2Gi
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: limber
      namespace: limber
      labels:
        instance: limber
    spec:
      limits:
        - type: Container
          min:
            cpu: 10m
            memory: 20Mi
          max:
            cpu: 500m
            memory: 1Gi
          default:
            cpu: 200m
            memory: 400Mi
          defaultRequest:
            cpu: 200m
            memory: 400Mi
