################################################################
# Docker Images                                                #
################################################################

image_gcloud: &image_gcloud
  image: google/cloud-sdk:latest

image_java: &image_java
  image: circleci/openjdk:8-jdk

image_mongo: &image_mongo
  image: circleci/mongo:3

image_node: &image_node
  image: circleci/node:12

################################################################
# CircleCI Caching                                             #
################################################################

save_backend_wrapper_cache: &save_backend_wrapper_cache
  save_cache:
    key: backend-wrapper-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
      - ~/.gradle/wrapper

restore_backend_wrapper_cache: &restore_backend_wrapper_cache
  restore_cache:
    keys:
      - backend-wrapper-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

save_backend_dependencies_cache: &save_backend_dependencies_cache
  save_cache:
    key: backend-dependencies-v1-{{ checksum "gradle/dependencies.gradle" }}
    paths:
      - ~/.gradle/caches

restore_backend_dependencies_cache: &restore_backend_dependencies_cache
  restore_cache:
    keys:
      - backend-dependencies-v1-{{ checksum "gradle/dependencies.gradle" }}

save_web_dependencies_cache: &save_web_dependencies_cache
  save_cache:
    key: web-dependencies-v1-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

restore_web_dependencies_cache: &restore_web_dependencies_cache
  restore_cache:
    keys:
      - web-dependencies-v1-{{ checksum "yarn.lock" }}
      - web-dependencies-v1-

################################################################
# Version                                                      #
################################################################

version: 2

################################################################
# Notifications                                                #
################################################################

experimental:
  notify:
    branches:
      only:
        - master

################################################################
# Workflows                                                    #
################################################################

workflows:

  version: 2

  feature-branches:
    jobs:
      - backend-dependencies:
          filters:
            branches:
              ignore:
                - feature/46-app-engine
      - backend-lint:
          requires: [backend-dependencies]
      - backend-test:
          requires: [backend-dependencies]
      - web-dependencies:
          filters:
            branches:
              ignore:
                - feature/46-app-engine
      - web-lint:
          requires: [web-dependencies]
      - web-test:
          requires: [web-dependencies]

  feature/46-app-engine:
    jobs:
      - backend-dependencies:
          filters:
            branches:
              only:
                - feature/46-app-engine
      - backend-lint:
          requires: [backend-dependencies]
      - backend-test:
          requires: [backend-dependencies]
      - web-dependencies:
          filters:
            branches:
              only:
                - feature/46-app-engine
      - web-lint:
          requires: [web-dependencies]
      - web-test:
          requires: [web-dependencies]
      - web-build:
          requires: [web-test]
      - deploy:
          requires:
            - backend-test
            - web-build

################################################################
# Jobs                                                         #
################################################################

checkout: &checkout
  checkout:
    path: ~/limber

jobs:

  backend-dependencies:
    docker: [*image_java]
    working_directory: ~/limber
    steps:
      - *checkout
      - *restore_backend_wrapper_cache
      - *restore_backend_dependencies_cache
      - run: ./gradlew --no-daemon downloadDependencies
      - *save_backend_wrapper_cache
      - *save_backend_dependencies_cache

  backend-lint:
    docker: [*image_java]
    working_directory: ~/limber
    steps:
      - *checkout
      - *restore_backend_wrapper_cache
      - *restore_backend_dependencies_cache
      - run: ./gradlew --no-daemon detekt

  backend-test:
    docker: [*image_java, *image_mongo]
    working_directory: ~/limber
    steps:
      - *checkout
      - *restore_backend_wrapper_cache
      - *restore_backend_dependencies_cache
      - run: ./gradlew --no-daemon test

  web-dependencies:
    docker: [*image_node]
    working_directory: ~/limber/limber-web
    steps:
      - *checkout
      - *restore_web_dependencies_cache
      - run: yarn install
      - *save_web_dependencies_cache

  web-lint:
    docker: [*image_node]
    working_directory: ~/limber/limber-web
    steps:
      - *checkout
      - *restore_web_dependencies_cache
      - run: yarn lint

  web-test:
    docker: [*image_node]
    working_directory: ~/limber/limber-web
    steps:
      - *checkout
      - *restore_web_dependencies_cache
      - run: yarn test

  web-build:
    docker: [*image_node]
    working_directory: ~/limber/limber-web
    steps:
      - *checkout
      - *restore_web_dependencies_cache
      - run: yarn build
      - persist_to_workspace:
          root: build
          path: '**/*'

  deploy:
    docker: [*image_java]
    working_directory: ~/limber
    steps:
      - *checkout
      - attach_workspace:
          root: .
          path: limber-backend-application/src/main/webapp
      - run: ./gradlew limber-backend-application:appengineDeploy

