name: Upload JAR files
description: Uploads all Server JAR files.
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: jar-files
        path: server/*/build/libs/server.jar
        retention-days: 1
