name: Set up Java
description: |
  Sets up Java.
  The gradle-cleanup action should be used at the end of jobs that use this action.
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3.4.1
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
