# This file extends Detekt's default default-detekt-config.yml.
# When upgrading Detekt versions, that file against its previous version
# and decide which changes to make in this file.

build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true

processors:
  active: false

console-reports:
  active: true

output-reports:
  active: false

comments:
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  OutdatedDocumentation:
    active: true

complexity:
  LargeClass:
    active: true
    threshold: 300
  LongMethod:
    active: true
    threshold: 30
  MethodOverloading:
    active: true
  NamedArguments:
    active: true
  NestedScopeFunctions:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true

coroutines:
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true

exceptions:
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  ThrowingExceptionInMain:
    active: true

formatting:
  AnnotationSpacing:
    active: true
  ArgumentListWrapping:
    active: true
    indentSize: 2
  BlockCommentInitialStarAlignment:
    active: true
  CommentWrapping:
    active: true
    indentSize: 2
  DiscouragedCommentLocation:
    active: true
  EnumEntryNameCase:
    active: true
  Filename:
    active: false # Overlaps with naming>MatchingDeclarationName.
  FunKeywordSpacing:
    active: true
  FunctionTypeReferenceSpacing:
    active: true
  Indentation:
    active: true
    indentSize: 2
  KdocWrapping:
    active: true
    indentSize: 2
  ModifierListSpacing:
    active: true
  MultiLineIfElse:
    active: true
  NoEmptyFirstLineInMethodBlock:
    active: true
  PackageName:
    active: true
  SpacingAroundAngleBrackets:
    active: true
  SpacingAroundDoubleColon:
    active: true
  SpacingAroundUnaryOperator:
    active: true
  SpacingBetweenDeclarationsWithAnnotations:
    active: true
  SpacingBetweenDeclarationsWithComments:
    active: true
  TrailingComma:
    active: true
    allowTrailingComma: true
    allowTrailingCommaOnCallSite: true
  TypeArgumentListSpacing:
    active: true
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true

naming:
  BooleanPropertyNaming:
    active: true
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][a-zA-Z0-9]*' # Enums should be PascalCase.
  FunctionMaxLength:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 3
  InvalidPackageDeclaration:
    active: true
    rootPackage: 'limber'
    requireRootInDeclaration: true
  LambdaParameterNaming:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  ObjectPropertyNaming:
    active: true
    constantPattern: '[a-z][A-Za-z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'
    privatePropertyPattern: '[a-z][A-Za-z0-9]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'
    privatePropertyPattern: '[a-z][A-Za-z0-9]*'
  VariableMaxLength:
    active: true
    maximumVariableNameLength: 30
  VariableMinLength:
    active: true
    minimumVariableNameLength: 3
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '[a-z][A-Za-z0-9]*'

performance:
  CouldBeSequence:
    active: true

potential-bugs:
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  ExitOutsideMain:
    active: true
  ImplicitUnitReturnType:
    active: true
  LateinitUsage:
    active: true
  MissingPackageDeclaration:
    active: true
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true

style:
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ForbiddenComment:
    active: false
  ForbiddenImport:
    active: true
    # Keep these in sync with IntelliJ auto-import exclusions (codeInsightSettings.xml).
    imports:
      - 'javax.inject.*'
      - 'org.slf4j.Logger'
      - 'org.slf4j.LoggerFactory'
  ForbiddenMethodCall:
    active: true
    methods:
      - 'kotlin.io.print'
      - 'kotlin.io.println'
  MagicNumber:
    active: false
  MandatoryBracesLoops:
    active: true
  ModifierOrder:
    active: false # Overlaps with formatting>ModifierOrdering.
  MultilineLambdaItParameter:
    active: true
  NewLineAtEndOfFile:
    active: false # Overlaps with formatting>FinalNewline.
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  OptionalWhenBraces:
    active: true
  RedundantExplicitType:
    active: true
  ReturnCount:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryAbstractClass:
    active: false
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  WildcardImport:
    active: true
    excludeImports: []
