name: Push Docker images
description: Pushes the Docker image for each Server.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        for d in server/*/; do
          image_name="us-docker.pkg.dev/circular-genius/limber/limber-$(basename "$d")-server"
          docker push "${image_name}:${GITHUB_SHA_SHORT}"
        done
