extends: production

rest:
  type: Merge
  value:
    parallelization:
      type: Replace
      value:
        connectionGroupSize: 4
        workerGroupSize: 8
        callGroupSize: 16
    shutDown:
      type: Replace
      value:
        gracePeriodMillis: 400
        timeoutMillis: 5000 # 5 seconds.

server:
  type: Merge
  value:
    lifecycle:
      type: Replace
      value:
        startupDelayMs: 400
        shutdownDelayMs: 200

sql:
  type: Merge
  value:
    jdbcUrl:
      type: Replace
      value:
        type: Plaintext
        value: jdbc:postgresql://localhost/limber
    username:
      type: Remove
    password:
      type: Remove
    migrations:
      type: Merge
      value:
        locations:
          - db/limber/migration/common
          - db/limber/migration/fixtures
    connectionTimeoutMs: 1000
    minimumIdle: 2
    maximumPoolSize: 8
