extends: production

rest:
  type: Merge
  value:
    parallelization:
      type: Replace
      value:
        connectionGroupSize: 4
        workerGroupSize: 8
        callGroupSize: 16
    shutDown:
      type: Replace
      value:
        gracePeriodMillis: 400
        timeoutMillis: 5000 # 5 seconds.

server:
  type: Merge
  value:
    lifecycle:
      type: Replace
      value:
        startupDelayMs: 400
        shutdownDelayMs: 200
