extends: local-production

auth0:
  type: Replace
  value:
    managementApi:
      type: Fake

event:
  type: Merge
  value:
    publish:
      type: Remove

sql:
  type: Merge
  value:
    jdbcUrl: jdbc:postgresql://localhost/limber
    username:
      type: Remove
    password:
      type: Remove
    migrations:
      type: Merge
      value:
        run: true
        cleanOnValidationError: true
        cleanDisabled: false
        locations:
          - db/limber/migration/common
          - db/limber/migration/fixtures
