extends: production

rest:
  type: Merge
  value:
    auth:
      type: Merge
      value:
        jwtLeeway: 300 # 5 minutes.
    parallelization:
      type: Replace
      value:
        connectionGroupSize: 4
        workerGroupSize: 8
        callGroupSize: 16
    port: 8080
    shutDown:
      type: Replace
      value:
        gracePeriodMs: 400
        timeoutMs: 5000 # 5 seconds.

server:
  type: Merge
  value:
    lifecycle:
      type: Replace
      value:
        startupDelayMs: 400
        shutdownDelayMs: 200

sql:
  type: Merge
  value:
    password:
      type: Replace
      value:
        type: Command
        command: gcloud auth print-access-token
    properties:
      type: Remove
    migrations:
      type: Merge
      value:
        run: true # TODO: Disable once migrations are stable.
        cleanOnValidationError: true # TODO: Disable once migrations are stable.
        cleanDisabled: false # TODO: Enable once migrations are stable.
    connectionTimeoutMs: 1000 # 1 second.
    minimumIdle: 2
    maximumPoolSize: 8
