extends: development

sql:
  type: Merge
  value:
    jdbcUrl:
      type: Replace
      value:
        type: EnvironmentVariable
        name: LIMBER_SQL_JDBC_URL # This must be set in the environment for the config to work.
    username:
      type: Replace
      value:
        type: EnvironmentVariable
        name: LIMBER_SQL_USERNAME # This must be set in the environment for the config to work.
    password:
      type: Replace
      value:
        type: Command
        command: gcloud auth print-access-token
    migrations:
      type: Merge
      value:
        run: true # TODO: Disable once migrations are stable.
        cleanOnValidationError: true # TODO: Disable once migrations are stable.
        cleanDisabled: false # TODO: Enable once migrations are stable.
        locations:
          - db/limber/migration/common
          - db/limber/migration/fixtures # TODO: Remove once migrations are stable.
          - db/limber/migration/gcp
