auth0:
  managementApi:
    type: Real
    domain: limber.auth0.com
    clientId: XcqhJx3jOBJfMSVQFGkLSqdHQeuHIyzx
    clientSecret:
      type: GcpSecret
      id: projects/225278732028/secrets/auth0-client-secret/versions/4

clock:
  type: Real

event:
  projectName: limberapp-io
  publish:
    shutdownMs: 5000 # 5 seconds.
  subscribe:
    startupMs: 5000 # 5 seconds.
    shutdownMs: 5000 # 5 seconds.
    maxOutstandingElements: 100
    maxOutstandingBytes: 104857600 # 100 MB.
    minimumBackoffMs: 10000 # 10 seconds.
    maximumBackoffMs: 600000 # 10 minutes.

ids:
  generation: Random

name: monolith

rest:
  allowedHosts:
    - localhost:3000
  auth:
    jwtClaimPrefix: https://limberapp.io/
    jwtIssuer: https://limber.auth0.com/
    jwtLeeway: 20 # 20 seconds.
    jwkDomain: limber.auth0.com
  parallelization:
    connectionGroupSize: 16
    workerGroupSize: 32
    callGroupSize: 64
  port:
    type: EnvironmentVariable
    name: PORT
  serverName: Limber
  shutDown:
    gracePeriodMs: 5000 # 5 seconds.
    timeoutMs: 12000 # 12 seconds.

restClient:
  baseUrls:
    self: http://localhost:8080/

server:
  lifecycle:
    startupDelayMs: 2000 # 2 seconds.
    shutdownDelayMs: 4000 # 4 seconds.

sql:
  jdbcUrl:
    type: EnvironmentVariable
    name: LIMBER_SQL_JDBC_URL
  username:
    type: EnvironmentVariable
    name: LIMBER_SQL_USERNAME
  password:
    type: GcpSecret
    id: projects/225278732028/secrets/sql-limber-app-engine-password/versions/3
  properties:
    socketFactory: com.google.cloud.sql.postgres.SocketFactory
    cloudSqlInstance:
      type: EnvironmentVariable
      name: LIMBER_SQL_INSTANCE_NAME
      ipTypes: PUBLIC
  migrations:
    run: true
    cleanOnValidationError: false
    cleanDisabled: true
    locations:
      - db/limber/migration/common
      - db/limber/migration/fixtures # TODO: Remove once migrations are stable.
      - db/limber/migration/gcp
    defaultSchema: public
    schemas:
      - form
      - organization
  connectionTimeoutMs: 2000 # 2 seconds.
  minimumIdle: 8
  maximumPoolSize: 32
