clock:
  type: Real

guids:
  generation: Random

name: monolith

rest:
  allowedHosts: []
  parallelization:
    connectionGroupSize: 16
    workerGroupSize: 32
    callGroupSize: 64
  port: 8080
  serverName: Limber
  shutDown:
    gracePeriodMillis: 5000 # 5 seconds.
    timeoutMillis: 12000 # 12 seconds.

restClient:
  baseUrls:
    self: http://localhost:8080/ # Using K8s DNS would introduce a catch-22 for the readiness check.

server:
  lifecycle:
    startupDelayMs: 2000 # 2 seconds.
    shutdownDelayMs: 4000 # 4 seconds.
