apiVersion: apps/v1
kind: Deployment
metadata:
  name: limber-monolith-server
  namespace: limber
  labels:
    instance: limber
spec:
  selector:
    matchLabels:
      app: limber-monolith-server
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: limber-monolith-server
    spec:
      serviceAccountName: limber-service-account
      containers:
        - name: server
          image: us-docker.pkg.dev/circular-genius/limber/limber-monolith-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 425m
              memory: 900M
          ports:
            - containerPort: 8080
          env:
            - name: LIMBER_CONFIG
              value: production
            - name: LIMBER_SQL_JDBC_URL
              value: jdbc:postgresql://localhost/limber
            - name: LIMBER_SQL_USERNAME
              value: limber
            - name: LIMBER_SQL_PASSWORD_SECRET_ID
              value: projects/circular-genius/secrets/sql-limber-limber-password/versions/latest
            - name: LOG_FORMAT
              value: GCP_JSON
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 6
            failureThreshold: 12
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.31.2 # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
          command:
            - "/cloud_sql_proxy"
            - "-instances=circular-genius:us-central1:limber=tcp:5432"
            - "-log_debug_stdout"
          resources:
            requests:
              cpu: 75m
              memory: 100M
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"] # The proxy should only stop once the app has stopped.
          securityContext:
            runAsNonRoot: true
