apiVersion: v1
kind: Service
metadata:
  name: limber-monolith-server
  namespace: limber
  labels:
    instance: limber
  annotations:
    cloud.google.com/backend-config: '{ "default": "limber-backend-config" }'
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: limber-monolith-server
