apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: Service
    metadata:
      name: hello
      namespace: limber
      labels:
        instance: limber
      annotations:
        cloud.google.com/backend-config: '{ "default": "firewall" }'
    spec:
      ports:
        - port: 80
          targetPort: 5050
      selector:
        app: hello

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hello
      namespace: limber
      labels:
        instance: limber
    spec:
      selector:
        matchLabels:
          app: hello
      replicas: 2
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      template:
        metadata:
          labels:
            app: hello
        spec:
          serviceAccountName: limber
          containers:
            - name: server
              image: vad1mo/hello-world-rest:latest
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 500m
                  memory: 1000M
              ports:
                - containerPort: 5050
              livenessProbe:
                httpGet:
                  path: /health-check
                  port: 5050
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 12
              readinessProbe:
                httpGet:
                  path: /health-check
                  port: 5050
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 6
                failureThreshold: 12
