name: Upload Yarn files
description: Uploads all Yarn build files.
runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@v3.1.1 # https://github.com/actions/upload-artifact/releases.
      with:
        name: yarn-files
        path: web/build/
        retention-days: 1
