mongoDatabase:
  protocol: MONGODB
  host: localhost
  database: limberapp

authentication:
  mechanisms:
    - type: JWT
      issuer: https://limberapp.io/
      secret: limberapp
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  apiPathPrefix: /
  staticFiles:
    serve: false
