mongoDatabase:
  protocol: MONGODB
  host: localhost
  database: limberapp

authentication:
  mechanisms:
    - type: JWT
      secret: limberapp

serving:
  apiPathPrefix: /
  staticFiles:
    serve: false
