sqlDatabase:
  jdbcUrl:
    type: PLAINTEXT
    value: jdbc:postgresql://localhost/limber
  username: postgres
  connectionTimeout: 1000
  maximumPoolSize: 2

authentication:
  mechanisms:
    - type: JWT
      issuer: https://limberapp.io/
      secret: limber
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

hashing:
  logRounds: 12

serving:
  redirectHttpToHttps: false
  apiPathPrefix: /
  staticFiles:
    serve: false
