sqlDatabase:
  jdbcUrl: jdbc:postgresql://35.203.81.79/limber
  username: limber
  password:
    type: ENVIRONMENT_VARIABLE
    value: LIMBER_PROD_POSTGRES_PASSWORD
  connectionTimeout: 1000
  maximumPoolSize: 2

authentication:
  mechanisms:
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  apiPathPrefix: /api
  staticFiles:
    serve: true
    rootPath: ../../src/main/webapp
