sqlDatabase:
  jdbcUrl: jdbc:postgresql:///limber
  username: limber
  password:
    type: PLAINTEXT
    value: H731t4zJsoRUKE$7%vS$D9WA

authentication:
  mechanisms:
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  apiPathPrefix: /api
  staticFiles:
    serve: true
    rootPath: .
