sqlDatabase:
  jdbcUrl: jdbc:postgresql:///limber
  username: limber
  password:
    type: ENVIRONMENT_VARIABLE
    value: LIMBER_PROD_POSTGRES_PASSWORD
  connectionTimeout: 2500
  maximumPoolSize: 10

authentication:
  mechanisms:
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  redirectHttpToHttps: true
  apiPathPrefix: /
  staticFiles:
    serve: false
