sqlDatabase:
  jdbcUrl: jdbc:postgresql://localhost/limber
  username: limber

authentication:
  mechanisms:
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  apiPathPrefix: /api
  staticFiles:
    serve: true
    rootPath: .
