sqlDatabase:
  jdbcUrl: jdbc:postgresql://34.68.206.182/limber
  username: limber
  password:
    type: ENVIRONMENT_VARIABLE
    value: LIMBER_PROD_POSTGRES_PASSWORD

authentication:
  mechanisms:
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  apiPathPrefix: /api
  staticFiles:
    serve: true
    rootPath: limber-backend-application/src/main/webapp
