sqlDatabase:
  jdbcUrl:
    type: ENVIRONMENT_VARIABLE
    value: LIMBER_PROD_POSTGRES_JDBC_URL
  username: limber
  password:
    type: ENVIRONMENT_VARIABLE
    value: LIMBER_PROD_POSTGRES_PASSWORD
  connectionTimeout: 2500
  maximumPoolSize: 8

authentication:
  mechanisms:
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  redirectHttpToHttps: false
  apiPathPrefix: /
  staticFiles:
    serve: false
