kmsConfig:
  project: limber-main
  location: global
  keyRing: limber
  cryptoKey: secrets

sqlDatabase:
  jdbcUrl: jdbc:postgresql:///limber
  username: limber
  password:
    type: ENCRYPTED
    value: CiQA06vbeIEEpB4fagiXm1yZhdpiKI6ift932S+fap8Mvsf7Q1ASQQDbebrMAypLHIDJSHAhp16pMw5/JKR2lvO0bhX7Ux6h2Jv9UiP9b9fA51Gr7RABpOtfMywGvap2FmsIGOwqNyRM
  connectionTimeout: 2500
  maximumPoolSize: 10
  properties:
    # https://cloud.google.com/sql/docs/mysql/connect-app-engine
    socketFactory: com.google.cloud.sql.postgres.SocketFactory
    cloudSqlInstance: limber-main:northamerica-northeast1:limber-prod
    useSSL: false

authentication:
  mechanisms:
    - type: JWK
      issuer: https://limber.auth0.com/
      domain: limber.auth0.com

serving:
  apiPathPrefix: /api
  staticFiles:
    serve: true
    rootPath: .
