sqlDatabase:
  jdbcUrl:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_PROD_POSTGRES_JDBC_URL
  username:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_PROD_POSTGRES_USERNAME
  password:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_PROD_POSTGRES_PASSWORD
  connectionTimeout: 2500
  maximumPoolSize: 8

authentication:
  mechanisms:
    - type: JWT
      issuer: https://limberapp.io/
      leeway: 20 # 20 seconds
      secret:
        type: ENVIRONMENT_VARIABLE
        name: LIMBER_PROD_JWT_SECRET
    - type: JWK
      issuer: https://limber.auth0.com/
      leeway: 20 # 20 seconds
      domain: limber.auth0.com

hashing:
  logRounds: 12

serving:
  redirectHttpToHttps: false
  apiPathPrefix: /
  staticFiles:
    serve: false
