sqlDatabase:
  jdbcUrl:
    type: PLAINTEXT
    value: jdbc:postgresql://localhost/limber_test
  username:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_PROD_POSTGRES_USERNAME
    defaultValue: postgres
  password:
    type: ENVIRONMENT_VARIABLE
    name: LIMBER_PROD_POSTGRES_PASSWORD
  connectionTimeout: 1000
  maximumPoolSize: 2

authentication:
  mechanisms:
    - type: UNSIGNED_JWT
      leeway: 0

hashing:
  logRounds: 4

serving:
  redirectHttpToHttps: false
  apiPathPrefix: /
  staticFiles:
    serve: false
