name: CI (Kotlin)

on:
  pull_request:
    paths:
      - .detekt/**
      - .github/**
      - buildSrc/**
      - common/**
      - db/**
      - feature/**
      - gradle/**
      - server/**
      - gradlew
      - settings.gradle.kts
  push:
    branches: [main]

concurrency:
  group: ci-kotlin-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: limber
          POSTGRES_PASSWORD: limber
          POSTGRES_DB: limber_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out
        uses: actions/checkout@v3.1.0 # https://github.com/actions/checkout/releases.
      - name: Set up Java
        uses: ./.github/actions/set-up-java
      - name: Gradle build
        uses: ./.github/actions/gradle-build
        with:
          postgresUsername: limber
          postgresPassword: limber
      - name: Upload JAR files
        uses: ./.github/actions/upload-gradle-files
      - name: Gradle cleanup
        if: always()
        uses: ./.github/actions/gradle-cleanup
