name: CI

on:
  push:
    branches-ignore:
      - master

jobs:

  backend-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
#      - restore_backend_wrapper_cache
#      - restore_backend_dependencies_cache
      - run: ./gradlew --no-daemon downloadDependencies
#      - save_backend_wrapper_cache
#      - save_backend_dependencies_cache

  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
#      - restore_backend_wrapper_cache
#      - restore_backend_dependencies_cache
      - run: bash ./gradlew --no-daemon detekt

  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: limber_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1.3.0
          with:
            java-version: 1.8
#      - restore_backend_wrapper_cache
#      - restore_backend_dependencies_cache
      - run: bash ./gradlew --no-daemon test --info --stacktrace
