name: CI

on:
  push:
    branches-ignore:
      - master

jobs:

  backend-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-dependencies-v1-${{ hashFiles('gradle/dependencies.gradle', '**/build.gradle') }}
      - run: ./gradlew --no-daemon downloadDependencies

  backend-lint:
    runs-on: ubuntu-latest
    needs: backend-dependencies
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-dependencies-v1-${{ hashFiles('gradle/dependencies.gradle', '**/build.gradle') }}
      - run: bash ./gradlew --no-daemon detekt

  backend-test:
    runs-on: ubuntu-latest
    needs: backend-dependencies
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: limber_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-dependencies-v1-${{ hashFiles('gradle/dependencies.gradle', '**/build.gradle') }}
      - run: bash ./gradlew --no-daemon test --info --stacktrace
