name: "Docs CI"

permissions:
  contents: "read"
  id-token: "write"
  pages: "write"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/docs-ci.yaml"
      - "docs/**"
      - "**/README.md"
      - "CHANGELOG.md"
  workflow_dispatch:

concurrency:
  group: "docs-ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out"
        uses: "actions/checkout@v6" # https://github.com/actions/checkout/releases
      - name: "GCP auth"
        uses: "google-github-actions/auth@v3" # https://github.com/google-github-actions/auth/releases
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Java"
        uses: "actions/setup-java@v5" # https://github.com/actions/setup-java/releases
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "gradle"
      - name: "Gradle dokka"
        run: |
          ./gradlew dokkaGenerate
      - name: "Set up pnpm"
        uses: "pnpm/action-setup@v4" # https://github.com/pnpm/action-setup/releases
        with:
          version: "10"
      - name: "Set up Node"
        uses: "actions/setup-node@v6" # https://github.com/actions/setup-node/releases
        with:
          node-version-file: "docs/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "docs/pnpm-lock.yaml"
      - name: "pnpm install"
        run: |
          pnpm install
        working-directory: "./docs"
      - name: "pnpm build"
        run: |
          pnpm build
        working-directory: "./docs"
