name: Kotlin

on:
  pull_request:
    paths:
      - .detekt/**
      - .github/**
      - buildSrc/**
      - common/**
      - db/**
      - feature/**
      - gradle/**
      - server/**
      - gradlew
      - settings.gradle.kts
  push:
    branches: [main]

concurrency:
  group: kotlin-${{ github.ref }}
  cancel-in-progress: true

jobs:

  CI:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: limber
          POSTGRES_PASSWORD: limber
          POSTGRES_DB: limber_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out
        uses: actions/checkout@v3.1.0
      - name: Set up Java
        uses: ./.github/actions/set-up-java
      - name: Gradle build
        uses: ./.github/actions/gradle-build
        with:
          postgresUsername: limber
          postgresPassword: limber
      - name: Upload JAR files
        uses: actions/upload-artifact@v3.1.1
        with:
          name: gradle-files
          path: server/*/build/libs/server.jar
          retention-days: 1
      - name: Gradle cleanup
        if: always()
        uses: ./.github/actions/gradle-cleanup

  CD:
    runs-on: ubuntu-22.04
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out
        uses: actions/checkout@v3.1.0
      - name: Download JAR files
        uses: actions/download-artifact@v3.0.1
        with:
          name: gradle-files
          path: server/
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy App Engine
        uses: google-github-actions/deploy-appengine@v1.1.0
        with:
          project_id: limberapp-io
          working_directory: server/monolith/
          deliverables: build/libs/server.jar
          flags: --appyaml=app.yaml
