name: "Kotlin CI"

permissions:
  contents: "read"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "kotlin-ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out"
        uses: "actions/checkout@v6" # https://github.com/actions/checkout/releases
      - name: "GCP auth"
        uses: "google-github-actions/auth@v3" # https://github.com/google-github-actions/auth/releases
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Hermit"
        uses: "cashapp/activate-hermit@v1" # https://github.com/cashapp/activate-hermit
        with:
          cache: "true"
      - name: "Set up Gradle"
        uses: "gradle/actions/setup-gradle@v5" # https://github.com/gradle/actions
      - name: "Gradle classes"
        run: |
          gradle classes testClasses
      - name: "Gradle test"
        run: |
          gradle test
      - name: "Gradle detekt"
        run: |
          gradle detektMain detektTest
