name: Kotlin CD

on:
  workflow_run:
    workflows: [Kotlin CI]
    types: [completed]
    branches: [main]

concurrency:
  group: kotlin-cd
  cancel-in-progress: true

jobs:

  docker:
    name: Docker promote
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out
        uses: actions/checkout@v3.0.2
      - name: Set commit hash
        uses: ./.github/actions/set-commit-hash
      - name: Authenticate with GCP
        uses: ./.github/actions/authenticate-with-gcp
        with:
          key: ${{ secrets.GCP_SA_KEY }}
      - name: Promote Docker images
        uses: ./.github/actions/promote-docker-images

  kubernetes:
    name: Kubernetes rollout
    runs-on: ubuntu-22.04
    needs: [docker]
    steps:
      - name: Check out
        uses: actions/checkout@v3.0.2
      - name: Authenticate with GCP
        uses: ./.github/actions/authenticate-with-gcp
        with:
          key: ${{ secrets.GCP_SA_KEY }}
      - name: Restart Kubernetes rollouts
        uses: ./.github/actions/restart-kubernetes-rollouts
