name: Kotlin CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: kotlin-ci-${{ github.event.number }}
  cancel-in-progress: true

jobs:

  gradle:
    name: Gradle build
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: limber
          POSTGRES_PASSWORD: limber
          POSTGRES_DB: limber_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out
        uses: actions/checkout@v3.0.2
      - name: Set up Java
        uses: ./.github/actions/set-up-java
      - name: Gradle build
        uses: ./.github/actions/gradle-build
        with:
          postgresUsername: limber
          postgresPassword: limber
      - name: Upload JAR files
        uses: ./.github/actions/upload-jar-files
      - name: Gradle cleanup
        if: always()
        uses: ./.github/actions/gradle-cleanup

  docker:
    name: Docker build/push
    runs-on: ubuntu-22.04
    needs: [gradle]
    steps:
      - name: Check out
        uses: actions/checkout@v3.0.2
      - name: Set commit hash
        uses: ./.github/actions/set-commit-hash
      - name: Authenticate with GCP
        uses: ./.github/actions/authenticate-with-gcp
        with:
          key: ${{ secrets.GCP_SA_KEY }}
      - name: Download JAR files
        uses: ./.github/actions/download-jar-files
      - name: Build Docker images
        uses: ./.github/actions/build-docker-images
      - name: Push Docker images
        uses: ./.github/actions/push-docker-images
