name: "Publish"

permissions:
  contents: "write"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out"
        uses: "actions/checkout@v6" # https://github.com/actions/checkout/releases
      - name: "GCP auth"
        uses: "google-github-actions/auth@v3" # https://github.com/google-github-actions/auth/releases
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: "Set up Hermit"
        uses: "cashapp/activate-hermit@v1" # https://github.com/cashapp/activate-hermit
        with:
          cache: "true"
      - name: "Set up Gradle"
        uses: "gradle/actions/setup-gradle@v5" # https://github.com/gradle/actions
      - name: "Compute version"
        id: "version"
        run: |
          echo "version=$(date -u '+%Y%m%d.%H%M%S')-$(git rev-parse --short=8 HEAD)" >> "$GITHUB_OUTPUT"
      - name: "Gradle publish"
        run: |
          gradle publish -Pversion="${{ steps.version.outputs.version }}"
      - name: "Tag"
        run: |
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
