name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: limber_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-java@v1.4.0
        with:
          java-version: 11
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-v2-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-dependencies-v2-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-dependencies-v2-
      - run: ./gradlew --info --stacktrace downloadDependencies
      - run: ./gradlew --info --stacktrace classes
      - run: ./gradlew --info --stacktrace testClasses
      - run: ./gradlew --info --stacktrace test
        env:
          LIMBER_TEST_POSTGRES_USERNAME: postgres
          LIMBER_TEST_POSTGRES_PASSWORD: postgres
      - run: ./gradlew --info --stacktrace detekt
      - run: ./gradlew --info --stacktrace build
        env:
          ENV: production
      - run: docker build -t registry.digitalocean.com/limber/limber-backend-monolith:$(git rev-parse HEAD) limber-backend/monolith
      - run: docker build -t registry.digitalocean.com/limber/limber-web:$(git rev-parse HEAD) limber-web
