name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: limber_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew --info --stacktrace test
        env:
          LIMBER_TEST_POSTGRES_USERNAME: postgres
          LIMBER_TEST_POSTGRES_PASSWORD: postgres
      - run: ./gradlew --info --stacktrace detekt
      - run: ./gradlew --info --stacktrace build -x test -x detekt
        env:
          ENV: production
      - run: docker build -t registry.digitalocean.com/limber/limber-graphql-server:$(git rev-parse HEAD) limber-backend/server/graphql
      - run: docker build -t registry.digitalocean.com/limber/limber-monolith-server:$(git rev-parse HEAD) limber-backend/server/monolith
      - run: docker build -t registry.digitalocean.com/limber/limber-web:$(git rev-parse HEAD) limber-web
  build-web:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14
      - uses: actions/cache@v2.1.3
        with:
          path: ~/limber-react/node_modules
          key: ${{ runner.os }}-node-modules-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-v2-
      - run: yarn install --immutable
        working-directory: limber-react
      - run: yarn relay
        working-directory: limber-react
      - run: yarn test
        working-directory: limber-react
        env:
          CI: true # https://github.com/facebook/create-react-app/issues/6899
      - run: yarn lint
        working-directory: limber-react
      - run: yarn build
        working-directory: limber-react
        env:
          CI: false # https://github.com/facebook/create-react-app/issues/3657
          REACT_APP_LIMBER_API_BASE_URL: https://api.limberapp.io
          REACT_APP_LIMBER_GRAPHQL_BASE_URL: https://api.limberapp.io
      - run: docker build -t registry.digitalocean.com/limber/limber-react:$(git rev-parse HEAD) limber-react
