name: Release (prod)

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    name: Deploy backend (prod)
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: limber_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-java@v1.4.0
        with:
          java-version: 11
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-v2-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-dependencies-v3-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-dependencies-v2-
      - run: ./gradlew --info --stacktrace downloadDependencies
      - run: ./gradlew --info --stacktrace classes
      - run: ./gradlew --info --stacktrace testClasses
      - run: ./gradlew --info --stacktrace test
        env:
          LIMBER_TEST_POSTGRES_USERNAME: postgres
          LIMBER_TEST_POSTGRES_PASSWORD: postgres
      - run: ./gradlew --info --stacktrace detekt
      - run: ./gradlew --info --stacktrace build
        env:
          ENV: production
      - run: docker login -u ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }} -p ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }} registry.digitalocean.com
      - run: docker build -t registry.digitalocean.com/limber/limber-monolith-server:master limber-backend/server/monolith
      - run: docker tag registry.digitalocean.com/limber/limber-monolith-server:master "registry.digitalocean.com/limber/limber-monolith-server:$(git rev-parse HEAD)"
      - run: docker push registry.digitalocean.com/limber/limber-monolith-server:master
      - run: docker push "registry.digitalocean.com/limber/limber-monolith-server:$(git rev-parse HEAD)"
      - run: docker build -t registry.digitalocean.com/limber/limber-web:master limber-web
      - run: docker tag registry.digitalocean.com/limber/limber-web:master "registry.digitalocean.com/limber/limber-web:$(git rev-parse HEAD)"
      - run: docker push registry.digitalocean.com/limber/limber-web:master
      - run: docker push "registry.digitalocean.com/limber/limber-web:$(git rev-parse HEAD)"
      - uses: digitalocean/action-doctl@v2.0.0
        with:
          token: ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save limber
      - run: kubectl set image deployment/limber-monolith-server limber-monolith-server="registry.digitalocean.com/limber/limber-monolith-server:$(git rev-parse HEAD)" --namespace limber
      - run: kubectl set image deployment/limber-web limber-web="registry.digitalocean.com/limber/limber-web:$(git rev-parse HEAD)" --namespace limber
  deploy-web:
    name: Deploy web (prod)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: 12
      - uses: actions/cache@v2.1.0
        with:
          path: ~/limber-react/node_modules
          key: ${{ runner.os }}-node-modules-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-v2-
      - run: yarn install --immutable
        working-directory: limber-react
      - run: yarn relay
        working-directory: limber-react
      - run: yarn test
        working-directory: limber-react
        env:
          CI: true # https://github.com/facebook/create-react-app/issues/6899
      - run: yarn lint
        working-directory: limber-react
      - run: yarn build
        working-directory: limber-react
        env:
          CI: false # https://github.com/facebook/create-react-app/issues/3657
          REACT_APP_LIMBER_API_BASE_URL: https://api.limberapp.io
          REACT_APP_LIMBER_GRAPHQL_BASE_URL: https://api.limberapp.io
      - run: docker login -u ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }} -p ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }} registry.digitalocean.com
      - run: docker build -t registry.digitalocean.com/limber/limber-react:master limber-react
      - run: docker tag registry.digitalocean.com/limber/limber-react:master "registry.digitalocean.com/limber/limber-react:$(git rev-parse HEAD)"
      - run: docker push registry.digitalocean.com/limber/limber-react:master
      - run: docker push "registry.digitalocean.com/limber/limber-react:$(git rev-parse HEAD)"
      - uses: digitalocean/action-doctl@v2.0.0
        with:
          token: ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save limber
      - run: kubectl set image deployment/limber-react limber-react="registry.digitalocean.com/limber/limber-react:$(git rev-parse HEAD)" --namespace limber
