name: Release (prod)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy (prod)
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: limber_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-dependencies-v1-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-dependencies-v1-
      - run: ./gradlew --info --stacktrace downloadDependencies
      - run: ./gradlew --info --stacktrace classes
      - run: ./gradlew --info --stacktrace testClasses
      - run: ./gradlew --info --stacktrace jvmTest jsTest test
        env:
          LIMBER_PROD_POSTGRES_PASSWORD: postgres
      - run: ./gradlew --info --stacktrace detekt
      - run: ./gradlew --info --stacktrace build
        env:
          ENV: production
      - run: docker login -u ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }} -p ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }} registry.digitalocean.com
      - run: docker build -t registry.digitalocean.com/limber-registry/limber-backend:master limber-backend-application
      - run: docker tag registry.digitalocean.com/limber-registry/limber-backend:master registry.digitalocean.com/limber-registry/limber-backend:$(git rev-parse HEAD)
      - run: docker push registry.digitalocean.com/limber-registry/limber-backend:master
      - run: docker push registry.digitalocean.com/limber-registry/limber-backend:$(git rev-parse HEAD)
      - run: docker build -t registry.digitalocean.com/limber-registry/limber-web:master limber-web
      - run: docker tag registry.digitalocean.com/limber-registry/limber-web:master registry.digitalocean.com/limber-registry/limber-web:$(git rev-parse HEAD)
      - run: docker push registry.digitalocean.com/limber-registry/limber-web:master
      - run: docker push registry.digitalocean.com/limber-registry/limber-web:$(git rev-parse HEAD)
      - uses: digitalocean/action-doctl@v1.8.0
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.LIMBER_DIGITAL_OCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-limber-prod > $GITHUB_WORKSPACE/.kubeconfig
      - run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig set image deployment/limber-backend limber-backend=registry.digitalocean.com/limber-registry/limber-backend:$(git rev-parse HEAD) --namespace limber
      - run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig set image deployment/limber-web limber-web=registry.digitalocean.com/limber-registry/limber-web:$(git rev-parse HEAD) --namespace limber
