name: Set up Node.js
description: Sets up Node.js.
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3.5.0
      with:
        node-version-file: web/.nvmrc
        cache: yarn
        cache-dependency-path: web/yarn.lock
